import { axios, base } from './../assets/js/axios-re'
export const projectId = params => axios.post(`${base}/manager`, params).then(res => res.data)
// export const jxWork = params => axios.post(`${base}/manager/jobCompletion`, params).then(res => res.data)
export const getPlus = params => axios.get(`${base}/manager/plus`, {params: params}).then(res => res.data)
export const jxPlus = params => axios.put(`${base}/manager/plus`, params).then(res => res.data)
export const jxReduct = params => axios.put(`${base}/manager/reduct`, params).then(res => res.data)
// export const jxQualitative = params => axios.post(`${base}/manager/qualitative`, params).then(res => res.data)
export const getReduct = params => axios.get(`${base}/manager/reduct`, {params: params}).then(res => res.data)
export const getRate = params => axios.get(`${base}/manager/triple`, {params: params}).then(res => res.data)
export const getWorkAndQua = params => axios.get(`${base}/manager/getWorkAndQua`, {params: params}).then(res => res.data)
export const updata = params => axios.post(`${base}/manager/newjxkh`, params).then(res => res.data)
export const jxQualitative = params => axios.post(`${base}/manager/allQualitative`, params).then(res => res.data)
export const jxWork = params => axios.post(`${base}/manager/allJobCompletion`, params).then(res => res.data)
export const saveAllJobCompletion = params => axios.post(`${base}/manager/saveAllJobCompletion`, params).then(res => res.data)
export const saveAllQualitative = params => axios.post(`${base}/manager/saveAllQualitative`, params).then(res => res.data)
export const totalPreview = params => axios.get(`${base}/manager/totalPreview`, {params: params}).then(res => res.data)
export const workPreview = params => axios.get(`${base}/manager/workPreview`, {params: params}).then(res => res.data)
export const qualitativePreview = params => axios.get(`${base}/manager/qualitativePreview`, {params: params}).then(res => res.data)
